- name: "Installing additonal sofwares"
  apt: pkg={{ item }} state=present
  with_items:
  - dnsutils
  - git
  - vim
  - ntp
  - at
  - lvm2

- name: "Adding bashrc"
  copy: src=../files/bash.bashrc dest=/etc/bash.bashrc owner=root group=root mode=0644

- name: "Removing deepak's barhrc"
  shell: creates=/home/deepak/.bashrc_backup mv /home/deepak/.bashrc /home/deepak/.bashrc_backup

- name: "root's bashrc"
  shell: creates=/root/.bashrc_backup mv /root/.bashrc /root/.bashrc_backup
