#---
- hosts: all
  become: true
  tasks:
  - name: Check if Docker is installed
    register: docker_installed
    command: docker -v
    ignore_errors: true

  - name: update the Linux system
    apt: 
       upgrade=dist
       update_cache=yes
    register: upgrade

  - name: Show the upgrade process    
    debug:
      msg: "{{ upgrade.stdout }}"
      
  - name: Install the certificates on the machine
    apt: name= {{ item }} state=latest
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: Add an apt key by id from a keyserver
    uri:
       url: https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e
       return_content: yes
    register: aptkey

  - name: Add a key from a file on the Ansible server
    apt_key:
       data: "{{ lookup(aptkey) }}"
       state: present

  - name: Add the repository for the docker
    apt_repository:
          repo: deb https://packages.docker.com/1.12/apt/repo/ \ubuntu-$(lsb_release -cs) \ main
          state: present

  - name: Install Docker
    apt: name=docker-engine state=latest
    when: docker_installed|failed
    
  - name: Display the Docker version installed
    debug:
      msg: "{{ docker_installed.stdout }}"
