#---
- hosts: all
  become: true
  tasks:
  - name: Check if Docker is installed
    register: docker_installed
    command: docker -v
    ignore_errors: true

  - name: update the Linux system
    apt: name=get state=latest

  - name: Install the certificates on the machine
    apt: name= {{ item }} state=latest
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: Add the repository to the docker.list
    command: echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list

  - name: Install Docker
    apt: name=docker-engine state=latest
    when: docker_installed|failed
    
  - name: Display the Docker version installed
    debug:
      msg: "{{ docker_installed.stdout }}"