#---
- hosts: all
  become: true
  tasks:
  - name: Check if Docker is installed
    register: docker_installed
    command: docker -v
    ignore_errors: true

  - name: This task is only executed if docker is installed
    debug: 
      var: docker_installed
    when: docker_installed|success
#    when: result is success  

  - name: This task is only executed if docker is NOT installed
    debug: 
      msg: 'docker is not installed'
    when: docker_installed|failed
#    when: result is failed

  - name: Install Docker
    apt: name=docker.io state=latest
    when: docker_installed|failed
