---
- name: Download  and unzip a zip file from internet the local machine
  hosts: all 
  become: true
  tasks: 
  - name: Download the java file first
    get_url: 
     url: https://downloads.git-tower.com/content/cheat-sheet-bundle.zip
     dest: /home/deepak/Downloads/
     mode: 0775
    register: DOWNLOADED
  - name: Unzip the downloaded file once it is downloaded
    unarchive: 
     src: /home/deepak/Downloads/cheat-sheet-bundle.zip
     dest: /home/deepak/Downloads/
     mode: 0775
    when: DOWNLOADED is successa
